### ISSUE TITLE
C1X or Cxense ?

### ISSUE THREAD

**Issue by njboro** [cXense/cxense-android#53]
Hi Folks,

Can someone, please tell me to implement PageView and Performance events, which one SDK from below I need to inject dependency in app level gradle : 
**1) Cxense SDK v2.4.0 
OR
2) C1x SDK v2.7.0
OR
3) Both ?**

**Comment by DeKaN** [comment]
Hi @njboro,

If you need only PV/Performance events and do not have access to Composer and C1x, use the latest version of Cxense SDK.  
C1x module (which depends on Cxense SDK) should be used if you use Composer Experiences in your app and you want to use C1x integration
