### ISSUE TITLE
The CxenseSdk.getInstance() function throws exception when used with version 2.6.0

### ISSUE THREAD

**Issue by wizard112** [cXense/cxense-android#59]
It seems that the function getInstance() of the SDK has the annotation "unused" and when we use it, we receive an exception with the following message : 
`java.lang.IllegalStateException: The Cxense SDK is not initialized! Make sure to call AppInitializer.getInstance(context).initializeComponent(CxSdkInitializer::class.java) before calling other methods.`

The start of the stack trace : 
`at io.piano.android.cxense.DependenciesProvider$Companion.getInstance(DependenciesProvider.kt:182)
 at io.piano.android.cxense.CxenseSdk$Companion.getInstance(CxenseSdk.kt:478)
...`

Example of using:
- CxenseSdk.getInstance().configuration
- CxenseSdk.getInstance().getUserSegments(...)
- PageViewEvent.Builder(...)
- ...

I did not find in the documentation a solution or an equivalent for CxenseSdk.getInstance()
Could you please tell me what is wrong ?

Thanks in advance.

**Comment by DeKaN** [comment]
Hi @wizard112,

SDK uses [AndroidX Startup library](https://developer.android.com/topic/libraries/app-startup) for initialization and looks like you've disabled it. Check that your app's merged manifest contains `<provider android:name="androidx.startup.InitializationProvider" ...><meta-data android:name="io.piano.android.cxense.CxSdkInitializer" .../>`

If you've disabled auto-initialization, call `AppInitializer.getInstance(context).initializeComponent(CxSdkInitializer::class.java)` as described in [documentation](https://developer.android.com/topic/libraries/app-startup#manual-initialization)

**Comment by wizard112** [comment]
Hi @DeKaN,

Thank you for the precision.

So I need to use `AppInitializer.getInstance(context).initializeComponent(CxSdkInitializer::class.java)` but your class **CxSdkInitializer** and **DependenciesProvider** are internal, if I want to create my own Initializer I need the function init of Cxense SDK but I don't know how initialize the Cxense SDK because the classes are internal

Is there any another solution ?

**Comment by DeKaN** [comment]
Hi @wizard112,
The best solution is "don't remove `androidx.startup.InitializationProvider` provider from app's manifest". But I'll make `CxSdkInitializer` public in the next release.

**Comment by DeKaN** [comment]
Hi @wizard112,
it will be available before Friday

**Comment by wizard112** [comment]
Hi @DeKaN ,
Okay, thank you.
We will use this new release.

**Comment by wizard112** [comment]
Hi @DeKaN,
Super ! We will upgrade the SDK.

**Comment by wizard112** [comment]
it works, thank you
